### ISSUE TITLE
Raycast goggle bug

### ISSUE THREAD

**Issue by AbomiNathan96** [SuperSpaceEye/Some-Peripherals#22]
My code with kick me from my server with the error on server:
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_18784(class_3244.java:214) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:247) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at net.spaceeye.someperipherals.items.goggles.RangeGogglesItem.raycastBatchRequest(RangeGogglesItem.java:52) ~[Some-Peripherals-0.0.12.jar:?]
	at net.spaceeye.someperipherals.items.goggles.RangeGogglesItem.method_7888(RangeGogglesItem.java:26) ~[Some-Peripherals-0.0.12.jar:?]
	at net.minecraft.class_1799.method_7917(class_1799.java:528) ~[server-intermediary.jar:?]
	at net.minecraft.class_1661.method_7381(class_1661.java:256) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_6007(class_1657.java:557) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2354) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:275) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14226(class_3222.java:478) ~[server-intermediary.jar:?]
	... 9 more

my code is:
gpu = peripheral.find("tm_gpu")
gog = peripheral.find("goggle_link_port")
scr =peripheral.find("monitor")
gogs = gog.getConnected()
for k, v in pairs(gogs) do
ray = v
break
end
rays = {}
CC = {}
BM = "block.minecraft."
CC[BM.."cobbled_deepslate"] = {25,25,25}
CC[BM.."bricks"] = {139,76,57}
CC[BM.."dirt"] = {85,64,39}
CC[BM.."air"] = {154,204,204}
gpu.refreshSize()
gpu.setSize(64)
print("gib res")
res = read()
IM = gpu.newImage(res*3,res*3)
gpu.fill(0,0,0)
R_L = {}
gpu.sync()
X = -64
Y = -64
for i = -res , res do
X = i

for I = -res , res do
Y = I
table.insert(R_L,{X,Y,nil})
end
end
while true do
ray.queueRaycasts(25,R_L,true)
while ray.getQueuedData()["is_done"] == true do
sleep(0)
end
Data = ray.getQueuedData()["results"]
for i,v in pairs(Data) do
print(i,v)
end
img = IM.ref()
gpu.drawImage(0,0,img)
sleep(1)
gpu.sync()
IM.free()
end

**Comment by AbomiNathan96** [comment]
I was about to say "nevermind im a idiot"
but there is a issue were if you make a batch raycast (even in euler mode) and have the last value as nil it will crash your game
