### ISSUE TITLE
NullPointerException On AutoStartUp

### ISSUE THREAD

**Issue by 19PHOBOSS98** [SuperSpaceEye/Some-Peripherals#8]
I got a few turtle drones setup to auto startup when I load in the world. Sometimes, when I'm too far away this shows up in their terminal:
![image](https://github.com/SuperSpaceEye/Some-Peripherals/assets/37253663/89242f08-9b22-4b13-96f4-fc21d1f19b4c)

I found this in the logs:
```
[24Nov2023 10:44:56.300] [ComputerCraft-Coroutine-1/ERROR] [computercraft/]: Error calling call on dan200.computercraft.core.apis.PeripheralAPI@3c97066a
java.lang.NullPointerException: null
	at net.spaceeye.someperipherals.utils.radar.ShipToMapKt.shipToMap(ShipToMapKt.java:98) ~[Some-Peripherals-0.0.8.jar%23119!/:?]
	at net.spaceeye.someperipherals.utils.radar.ScanInRadiusKt.scanForShips(ScanInRadiusKt.java:55) ~[Some-Peripherals-0.0.8.jar%23119!/:?]
	at net.spaceeye.someperipherals.utils.radar.ScanInRadiusKt.scanInRadius(ScanInRadiusKt.java:75) ~[Some-Peripherals-0.0.8.jar%23119!/:?]
	at net.spaceeye.someperipherals.integrations.cc.peripherals.RadarPeripheral.scan(RadarPeripheral.java:16) ~[Some-Peripherals-0.0.8.jar%23119!/:?]
	at net.spaceeye.someperipherals.integrations.cc.peripherals.RadarPeripheral$cc$scan138.apply(CC generated method) ~[?:?]
	at dan200.computercraft.shared.peripheral.modem.wired.WiredModemPeripheral$RemotePeripheralWrapper.callMethod(WiredModemPeripheral.java:409) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at dan200.computercraft.shared.peripheral.modem.wired.WiredModemPeripheral.callRemote(WiredModemPeripheral.java:212) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at dan200.computercraft.shared.peripheral.modem.wired.WiredModemPeripheral$cc$callRemote24.apply(CC generated method) ~[?:?]
	at dan200.computercraft.core.apis.PeripheralAPI$PeripheralWrapper.call(PeripheralAPI.java:112) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at dan200.computercraft.core.apis.PeripheralAPI.call(PeripheralAPI.java:361) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at dan200.computercraft.core.apis.PeripheralAPI$cc$call102.apply(CC generated method) ~[?:?]
	at dan200.computercraft.core.lua.ResultInterpreterFunction.invoke(ResultInterpreterFunction.java:61) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.function.ResumableVarArgFunction.invoke(ResumableVarArgFunction.java:77) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.function.LuaInterpreter.execute(LuaInterpreter.java:506) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.function.LuaInterpretedFunction.resume(LuaInterpretedFunction.java:196) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.debug.DebugFrame.resume(DebugFrame.java:243) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.LuaThread.loop(LuaThread.java:570) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at cc.tweaked.internal.cobalt.LuaThread$1.run(LuaThread.java:466) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at dan200.computercraft.core.lua.CobaltLuaMachine.lambda$new$1(CobaltLuaMachine.java:80) ~[cc-tweaked-1.18.2-1.101.3.jar%2365!/:1.101.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by SuperSpaceEye** [comment]
ok i think i know why this happened. this should be an easy fix

**Comment by SuperSpaceEye** [comment]
Will be fixed in the next update
